oracle:
  dsn: "YOUR_DB_HOST:1521/YOUR_SERVICE"
  user: "YOUR_ORACLE_USER"
  password: "YOUR_ORACLE_PASSWORD"

influx:
  url: "http://127.0.0.1:8086"
  org: "local"  
  bucket: "metrics"
  token: "dummy-token"

scheduler:
  weekdays: [0, 1, 2, 3, 4]
  start_hour: 9
  end_hour: 22
  query_timeout_ms: 10000

#ID Пользователей (Ю-шки)
user_mapping:
  "1001": "Alice Example"
  "1002": "Bob Example"
  "9999": "System"